# options(repos="https://stat.ethz.ch/CRAN/")
install.packages("tidytable")
install.packages("visNetwork")
install.packages("tarchetypes")
install.packages("here")
install.packages("janitor")
install.packages("kableExtra")
install.packages("qs")
install.packages("qs2")
install.packages("Hmisc")
install.packages("ggridges")
install.packages("modelsummary")
install.packages("caret")
install.packages("openai")